### ISSUE TITLE
Modal dialog keyboard close/cross icon is keyboard-focusable but visual outline is missing

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-desktop-ui#10]
RawGit:
~~https://rawgit.com/edrlab/r2-desktop-ui/master/index.html~~
https://edrlab.github.io/r2-desktop-ui/index.html

JSdelivr:
https://cdn.jsdelivr.net/gh/edrlab/r2-desktop-ui@cd28857ad53a498587e4c4828ba3ac5c140762e6/index.html

This problem is reproducible with other DOM elements.
To debug, I would suggest using this CSS snippet at the end of main.css (that's what I do to visually find out whether something is wrong with keyboard traversal):

```css
*:focus {
	outline-color: red;
	outline-width: 2px;
	outline-style: solid;
}
```
